[tool.poetry]
package-mode = false


[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
faker = "^24.11.0"
docker = "^7.0.0"
black = "^24.4.2"
pytest-asyncio = "^0.23.7"
